name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          # @todo use affected:build --base=origin/master but as we are using publishable libraries,
          # our libs like plugins depend on the core which should be built first and present in dist. 
          yarn ng build core --prod
          yarn ng build angular --prod
          yarn ng build plugin-auth --prod
          yarn ng build plugin-cache --prod
          yarn ng build plugin-retry --prod
          yarn ng build sandbox --prod

  e2e:
    runs-on: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: E2E
        run: |
          yarn run-p --race "start:api" "affected:e2e --base=origin/master --headless --parallel"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Test
        run: |
          yarn nx affected:test --base=origin/master --code-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
