name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn ng build core --prod
          yarn ng build angular --prod
          yarn ng build plugin-cache --prod
          yarn ng build sandbox --prod
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Test
        run: |
          yarn affected:test --base=remotes/origin/master --code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
